"""empty message

Revision ID: b58095453de1
Revises: 
Create Date: 2021-08-24 14:17:38.190903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58095453de1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('inn', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('client_info', sa.String(length=256), nullable=True),
    sa.Column('payment_account', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('t_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('t_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('err_code', sa.Integer(), nullable=True),
    sa.Column('err_message', sa.String(length=500), nullable=True),
    sa.Column('client_code', sa.String(length=64), nullable=True),
    sa.Column('branch_code', sa.String(length=64), nullable=True),
    sa.Column('manager_created_id', sa.Integer(), nullable=True),
    sa.Column('manager_confirm_id', sa.Integer(), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('date_confirm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['t_client.id'], ),
    sa.ForeignKeyConstraint(['manager_confirm_id'], ['t_manager.id'], ),
    sa.ForeignKeyConstraint(['manager_created_id'], ['t_manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('note_of_change', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('err_code', sa.Integer(), nullable=True),
    sa.Column('err_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['t_manager.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['t_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_order_history')
    op.drop_table('t_order')
    op.drop_table('t_manager')
    op.drop_table('t_client')
    # ### end Alembic commands ###
